[package]
name = "chacha"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
chacha20poly1305 = "0.10.1"
clip = "0.1.1"
clap = { version = "4.5.16", features = ["derive"] }
anyhow = "1.0.86"
